---
- hosts: all
  become: true
  remote_user: root
  become_method: sudo
  tasks:
    - name: Wait for instance to be reachable
      wait_for_connection:
        delay: 60
        timeout: 300
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
    # - name: Include the cisubuntu role
    #   include_role:
    #     name: cisubuntu
