---
- hosts: all
  vars:
    ansible_connection: community.aws.aws_ssm
    ansible_aws_ssm_region: "{{ aws_region }}"
    ansible_aws_ssm_bucket_name: "{{ ansible_bucket }}"
  become: true
  remote_user: root
  tasks:
    - name: Wait for instance to be reachable
      wait_for_connection:
        delay: 60
        timeout: 300
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: Include the cisubuntu role
      include_role:
        name: cisubuntu
