name: "Destroy Pipeline"

on:
  workflow_dispatch:

jobs:
  pipeline:
    name: "Destroy Pipeline"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ~0.14.r

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=$STATE_BUCKET_NAME" -backend-config="key=$STATE_BUCKET_KEY"
        env:
          STATE_BUCKET_NAME: ${{ secrets.STATE_BUCKET_NAME }}
          STATE_BUCKET_KEY: ${{ secrets.STATE_BUCKET_KEY }}

      - name: Terraform destroy
        run: terraform destroy -auto-approve
        env:
          TF_VAR_vpc_name: ${{ secrets.VPC_NAME }}
          TF_VAR_sg_name: ${{ secrets.SG_NAME }}
          TF_VAR_vpc_azs: ${{ secrets.VPC_AZS }}
          TF_VAR_vpc_cidr: ${{ secrets.VPC_CIDR }}
          TF_VAR_vpc_public_subnets: ${{ secrets.VPC_PUBLIC_SUBNETS }}
          TF_VAR_vpc_private_subnets: ${{ secrets.VPC_PRIVATE_SUBNETS }}
          TF_VAR_iam_role_name: ${{ secrets.IAM_ROLE_NAME }}
          TF_VAR_instance_name: ${{ secrets.INSTANCE_NAME }}
